name: The Love of my Life
favicon: null
layout_spectrum: 0.9999420745298266
typography_spectrum: 0.09347844240255654
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6355173278134316
  lightness: 0.330627131043002
  saturation: 0.11249085213057697
  rhythmicContrast: 0.24586930964142084
purpose: []
